# Generated by Django 4.0.2 on 2022-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggin',
            name='pasword',
            field=models.CharField(max_length=20),
        ),
    ]
