# Generated by Django 4.0.2 on 2022-03-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_loggin_pasword'),
    ]

    operations = [
        migrations.CreateModel(
            name='logginNEW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=20)),
                ('mobileno', models.IntegerField()),
                ('primaryemail', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
